# Form implementation generated from reading ui file 'agregarLibroView.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_AgregarLibro(object):
    def setupUi(self, MainWindow_AgregarLibro):
        MainWindow_AgregarLibro.setObjectName("MainWindow_AgregarLibro")
        MainWindow_AgregarLibro.resize(817, 747)
        MainWindow_AgregarLibro.setStyleSheet("background-color:back")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow_AgregarLibro)
        self.centralwidget.setObjectName("centralwidget")
        self.titulo_text = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.titulo_text.setGeometry(QtCore.QRect(310, 300, 104, 74))
        self.titulo_text.setObjectName("titulo_text")
        self.autor_text = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.autor_text.setGeometry(QtCore.QRect(90, 300, 104, 74))
        self.autor_text.setObjectName("autor_text")
        self.genero_text = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.genero_text.setGeometry(QtCore.QRect(590, 300, 104, 74))
        self.genero_text.setObjectName("genero_text")
        self.input_Autor = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.input_Autor.setGeometry(QtCore.QRect(80, 400, 113, 21))
        self.input_Autor.setObjectName("input_Autor")
        self.input_Genero = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.input_Genero.setGeometry(QtCore.QRect(580, 400, 113, 21))
        self.input_Genero.setObjectName("input_Genero")
        self.input_titulo = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.input_titulo.setGeometry(QtCore.QRect(310, 400, 113, 21))
        self.input_titulo.setObjectName("input_titulo")
        self.titulo_text_2 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.titulo_text_2.setGeometry(QtCore.QRect(160, 90, 451, 74))
        self.titulo_text_2.setObjectName("titulo_text_2")
        self.BT_agregarLIbro = QtWidgets.QPushButton(parent=self.centralwidget)
        self.BT_agregarLIbro.setGeometry(QtCore.QRect(140, 540, 100, 32))
        self.BT_agregarLIbro.setObjectName("BT_agregarLIbro")
        self.BT_regresar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.BT_regresar.setGeometry(QtCore.QRect(500, 540, 100, 32))
        self.BT_regresar.setObjectName("BT_regresar")
        self.BT_agregarUsuario = QtWidgets.QPushButton(parent=self.centralwidget)
        self.BT_agregarUsuario.setGeometry(QtCore.QRect(320, 540, 100, 32))
        self.BT_agregarUsuario.setObjectName("BT_agregarUsuario")
        MainWindow_AgregarLibro.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow_AgregarLibro)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 817, 24))
        self.menubar.setObjectName("menubar")
        MainWindow_AgregarLibro.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow_AgregarLibro)
        self.statusbar.setObjectName("statusbar")
        MainWindow_AgregarLibro.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_AgregarLibro)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_AgregarLibro)

    def retranslateUi(self, MainWindow_AgregarLibro):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_AgregarLibro.setWindowTitle(_translate("MainWindow_AgregarLibro", "MainWindow"))
        self.titulo_text.setHtml(_translate("MainWindow_AgregarLibro", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:700;\">TITULO<br /></span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt; font-weight:700;\"><br /></p></body></html>"))
        self.autor_text.setHtml(_translate("MainWindow_AgregarLibro", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:700;\">AUTOR</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt; font-weight:700;\"><br /></p></body></html>"))
        self.genero_text.setHtml(_translate("MainWindow_AgregarLibro", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:700;\">GENERO</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt; font-weight:700;\"><br /></p></body></html>"))
        self.titulo_text_2.setHtml(_translate("MainWindow_AgregarLibro", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:48pt;\">AGREGAR LIBRO<br /></span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:48pt;\"><br /></p></body></html>"))
        self.BT_agregarLIbro.setText(_translate("MainWindow_AgregarLibro", "Agregar libro"))
        self.BT_regresar.setText(_translate("MainWindow_AgregarLibro", "Regresar"))
        self.BT_agregarUsuario.setText(_translate("MainWindow_AgregarLibro", "Agregar Usuario"))
