# Form implementation generated from reading ui file 'loginView.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(817, 747)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.BT_login = QtWidgets.QPushButton(parent=self.frame)
        self.BT_login.setGeometry(QtCore.QRect(13, 497, 79, 32))
        self.BT_login.setObjectName("BT_login")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=self.frame)
        self.plainTextEdit.setGeometry(QtCore.QRect(13, 151, 767, 30))
        self.plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.plainTextEdit.setStyleSheet("\n"
" \n"
"        background-color: transparent;\n"
"        border: none;\n"
"        color: #4A90E2; /* Azul elegante */\n"
"        font-size: 24px;\n"
"        font-weight: bold;\n"
"        text-align: center;\n"
"    \n"
"\n"
"")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.login_input = QtWidgets.QTextEdit(parent=self.frame)
        self.login_input.setGeometry(QtCore.QRect(40, 330, 281, 20))
        self.login_input.setMaximumSize(QtCore.QSize(16777215, 20))
        self.login_input.setObjectName("login_input")
        self.rol_input = QtWidgets.QTextEdit(parent=self.frame)
        self.rol_input.setGeometry(QtCore.QRect(370, 330, 281, 20))
        self.rol_input.setMaximumSize(QtCore.QSize(16777215, 20))
        self.rol_input.setObjectName("rol_input")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 817, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.BT_login.setText(_translate("MainWindow", "Ingresar"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "LOGIN\n"
""))
